server:
  port: 8081
spring:
  application:
    name: consumer
  cloud:
    nacos:
      # Nacos 服务发现与注册配置
      discovery:
        server-addr: 172.0.0.1:18080
        username: nacos
        password: nacos
        namespace: be6ce011-8cf0-452d-934d-7db943424893
      config:
        server-addr: 172.0.0.1:18080
        username: nacos
        password: nacos
        namespace: be6ce011-8cf0-452d-934d-7db943424893

dubbo:
  registry:
    address: spring-cloud://172.0.0.1:18080?namespace=be6ce011-8cf0-452d-934d-7db943424893
  cloud:
    subscribed-services: provider
  consumer:
    timeout: 10000
    retries: 2
    loadbalance: roundrobin
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: 20880
